services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hris_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      TZ: Asia/Makassar
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hris_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: hris_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hris_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: hris_mysql
    restart: unless-stopped
    environment:
      TZ: Asia/Makassar
      MYSQL_DATABASE: hris
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: hris
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hris_network

  redis:
    image: redis:alpine
    container_name: hris_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hris_network

networks:
  hris_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
